# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  unity-portal-web:
    image: unity-portal-web
    build:
      context: .
      dockerfile: Unity.Portal.Web/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5080:5080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
