# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.9'

services:
  unity-portal-orchestrator:
    image: unity-portal-orchestrator
    build:
      context: /Unity.Portal.Orchestrator
      dockerfile: Dockerfile
      args:
        - configuration=Debug
    ports:
      - 6000:6000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
